apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    isDefault: true
    jsonData:
      defaultDatabase: logs
      protocol: native
      server: clickhouse
      port: 9000
      username: default
    secureJsonData:
      password: backtoeng
